k8sManagement:
    ipconfig:
        deployments:
            - ipAddress: 192.168.178.253
              namespace: example-project
              domain: example-project.domain.tld
            - ipAddress: 192.168.178.252
              namespace: example-project-dynamic
              domain: example-project.domain.tld
            - ipAddress: 10.15.15.1
              namespace: demo
              domain: demodomain.tld
            - ipAddress: 10.15.15.2
              namespace: demo-dev
              domain: demo-devdomain.tld
            - ipAddress: 10.15.15.3
              namespace: demo-qa
              domain: demo-qadomain.tld
            - namespace: demo-nginx
            - namespace: demo-reduced-nginxprj
