k8sJenkinsMgmt:
    ingress:
        namespace: example-project
        loadbalancerIp: 192.168.178.240
        deploymentName: nginx-ingress 
        jenkinsDeploymentName: jenkins-master
        jenkinsUriPrefix: /jenkins
        containerImage: bitnami/nginx-ingress-controller:latest
        imagePullSecrets:  
        controllerForNamespace:
            enabled: false
    loadbalancer:
        enabled: false 
        ports:
            http:
                port: 80 
                targetPort: 80 
            https:
                port: 443 
                targetPort: 443 
